In [1]:
#Vectors: A tuple of one or more values called scalars.

In [2]:
''' The Following examples are dealt with ROW Vectors.'''

' The Following examples are dealt with ROW Vectors.'

In [3]:
import numpy as np

#Define v1 
v1 = np.array( [ 1, 2, 0 ] )

#Define v2
v2 = np.array( [ 0, 1, 2 ] )

#Define v3 
v3 = np.array( [ 1, 0, 2 ] )

v = (v1, v2, v3)

print( "Vector v is:\n", v )

Vector v is:
 (array([1, 2, 0]), array([0, 1, 2]), array([1, 0, 2]))


In [4]:
#Vector Addition
v1_2 = v1 + v2

print( "Resultant Vector of v1 and v2:\n", v1_2 )

'''Another possibility is Subtraction. This is nothing but addition of vectors in 
different (opposite) directions.'''

#Example of vector subtraction.
v4 = np.array( [ -1, 0, -2 ] )

v1_4 = v1 + v4
print( "Resultant vector for V1 and v4 is : \n", v1_4 )

#Normal subtraction can also be performed.

v_sub = v3 - v1
print( "Difference Vector: \n", v_sub )

Resultant Vector of v1 and v2:
 [1 3 2]
Resultant vector for V1 and v4 is : 
 [ 0  2 -2]
Difference Vector: 
 [ 0 -2  2]


In [5]:
#Vector Multiplication
'''Vector multiplication:Let a and b be a vector of dim = (3,1), then a*b ==> a1*b1, a2*b2, a3*b3'''

v12 = v1 * v2
print( "Vector Product: ", v12 )

Vector Product:  [0 2 0]


In [6]:
#Vector Division
'''Vector Divison: Let a and b be two vector of dim = (3,1), then a/b when b is not Zero:
                                                                a1/b1, a2/b2, a3/b3'''

#Case -1: If one of the values is Zero, and Error will be raised
v1_div_v2 = v1 / v2

print( v1_div_v2 )

[inf  2.  0.]


<ipython-input-6-d1c44fc633be>:6: RuntimeWarning: divide by zero encountered in true_divide
  v1_div_v2 = v1 / v2


In [7]:
#case - 2: Non Zero Divisor

v1 = np.array( [ 1, 2, 3 ] )
v2 = np.array( [ -1, 1, 2 ] )

print( "v1 div v2: ", v1/v2 )
print( "v2 div v1: ", v2/v1 )

v1 div v2:  [-1.   2.   1.5]
v2 div v1:  [-1.          0.5         0.66666667]


In [8]:
#Dot Product of Vectors
""" The Scalar dot product of any two vectors resulting in Zro indicates that the two vectors are 
orthogonal to each other. """

''' a dot b ==> a1 * b1 + a2 * b2 + a3 * b3'''

v1_dot_v2 = v1.dot(v2)

print( "Dot product of v1 and v2 = ", v1_dot_v2 )

Dot product of v1 and v2 =  7


In [9]:
#Scalar Multiplication to a Vector
""" When a Scalar is multiplied to a vector, element wise multiplication for the whole 
vector by the scalar is performed. """

scalar = 0.5

vec1 = np.array( [ 10, 20, 30 ], dtype = 'float' )
vec2 = np.array( [ 4, 6, 8 ], dtype = 'float')
vec3 = np.array( [ 50, 100, 150 ], dtype = 'float' )

print( "vector_1 scaled by 0.5 is: ", scalar * vec1 )

scalar = -0.25
print( "vector_2 scaled by 0.5 is: ", scalar * vec2 )


scalar = 3
print( "vector_3 scaled by 0.5 is: ", scalar * vec3 )


""" See What happens when you try to multiply a scalar for a whole Tuple of vectors, 
it repeats itself. This is not what we expect."""

scalar = 5

vector = ( vec1, vec2, vec3 )

scalar_by_vector = scalar * vector

print( "\nUnwanted Output: \n",scalar_by_vector )

vector_1 scaled by 0.5 is:  [ 5. 10. 15.]
vector_2 scaled by 0.5 is:  [-1.  -1.5 -2. ]
vector_3 scaled by 0.5 is:  [150. 300. 450.]

Unwanted Output: 
 (array([10., 20., 30.]), array([4., 6., 8.]), array([ 50., 100., 150.]), array([10., 20., 30.]), array([4., 6., 8.]), array([ 50., 100., 150.]), array([10., 20., 30.]), array([4., 6., 8.]), array([ 50., 100., 150.]), array([10., 20., 30.]), array([4., 6., 8.]), array([ 50., 100., 150.]), array([10., 20., 30.]), array([4., 6., 8.]), array([ 50., 100., 150.]))


In [10]:
''' The Following examples are dealt with COLUMN Vectors.'''

' The Following examples are dealt with COLUMN Vectors.'

In [11]:
col_vec = np.array( [ [ 1 ], [ 2 ], [ 3 ] ] )
print( "Column Vector: \n", col_vec )

Column Vector: 
 [[1]
 [2]
 [3]]
